### PR TITLE
Added performance enhancements

### PR DESCRIPTION
**Pull request by rdv-dev**
This is linked to issue #4 .

The last sed script appears to be one of the slowest and most complex portion of this process. Unfortunately due to this complexity, it is hard to make good performance enhancements without introducing new bugs or finding a different solution for this part of the script. The enhancements made to the last sed script increase performance by about 7% . (big woop)

These enhancements make sense because it consolidates the 7 separate replacement commands into 4, streamlining the process. Additionally, the regular expressions are similar enough that consolidating them does not negatively impact readability too much.

The enhancements made to the awk script increase performance by at least 50% ! 

Previously, the awk script printed out each field individually, which is very inefficient. Concatenating together the fields into one string, then printing the string as one line increases the performance significantly by reducing the number of times print is called - a notoriously slow process.

Please let me know if you have any questions on this!

### CODE REVIEW

**Comment by minamotorin** [comment]
@algae-disco 
Thank you very much!
This is a great PR! I had not thought about performance of this script.

> The enhancements made to the awk script increase performance by at least 50% !

Oh that is amazing! I heard about the performance of `printf` for the first time. Could you tell me where I can find this information?

**Comment by rdv-dev** [comment]
> Could you tell me where I can find this information?

Sure!

There are lots of examples of print or printf being slow in general, it's not just a problem that affects awk.

Examples:
https://stackoverflow.com/questions/4437715/why-is-system-out-println-so-slow
https://www.quora.com/Do-print-statements-in-the-programming-language-slows-down-the-execution


Another example from ChatGPT with some specific optimization tips which are limited to Python but the general principle is the same:

===
The print() function in Python is a high-level operation that includes many steps under the hood. When you call print(), Python does the following:

1. It converts the objects you're printing to strings (if they're not already strings). This process involves calling the object's `__str__()` or `__repr__()` method and can take some time if the object is complex.

2. It adds spaces between the objects (or whatever character is specified as the sep parameter).

3. It adds a newline at the end (unless the end parameter is specified as something else).

4. It flushes the output buffer, writing the result to the console. This step involves a system call, which is a request to the operating system to perform an operation. In this case, the operation is writing data to the standard output, which is usually your console. **System calls are relatively slow because they involve a context switch from user mode to kernel mode**.

5. If you're printing to a file or other output stream, Python also has to perform I/O operations, which can be slow depending on the speed of your disk and the amount of data you're writing.

All of these steps take time, and they add up if you're calling print() in a loop or other frequently executed part of your code.

Appending strings before printing can be faster because you're reducing the number of system calls and I/O operations. You're also potentially reducing the number of object-to-string conversions and other operations that print() performs. Instead of performing these operations for each call to print(), you're performing them once for the entire concatenated string.

However, it's worth noting that Python's string concatenation can be inefficient if done incorrectly, because strings in Python are immutable. That means every time you concatenate two strings, Python has to allocate memory for a new string and copy the contents of the old strings into it. This can be slow if you're concatenating a large number of strings in a loop. To avoid this, you can use the join() method of strings, which concatenates a list of strings in a more efficient way.

Here's an example:

```
# Slow way:
s = ""
for substring in list_of_substrings:
    s += substring
print(s)

# Fast way:
s = "".join(list_of_substrings)
print(s)
```

In the first example, Python has to create a new string and copy the old strings into it for each iteration of the loop. In the second example, Python concatenates all the strings at once, which is much faster.

===

Also think of it this way. Let's say printf takes 2 cycles to start, 1 cycle to print whatever it needs to print, then 1 cycle to finish. So every printf command results in 4 cycles of processing time - which is really fast when the data set is small!
However, let's consider a large dataset with 40,000 rows and 25 columns (1,000,000 cells) .
If we print every cell individually, that will take 1000000 * 4 = 4,000,000 cycles!
If instead, we print every **line**, then it will take only 40000 * 4 = 160,000 cycles!
That's a factor of 25 times less processing time! 

Even though this is a simple example, the mathematical principle outlines the fact that calling print or printf less times will usually result in a faster program.

Anyway, I hope this helps you! I've really enjoyed contributing to your script - I needed it because some of the others on my team are not familiar with Linux (WSL) or the command-line, so I didn't want them to install anything - for example openpyxl . This script allows them to just run the program. I'm using this script at work to convert xlsx files to csv, then I wrote a separate script in awk to re-arrange the columns according to a mapping, transform some columns, and split the files based on a row count. All together it takes about 30 minutes to process 850 megabytes of data, which is pretty good!

**Comment by minamotorin** [comment]
@algae-disco 
Thanks. Your comment is very helpful.
This is general tips to make program faster.

The reason why I wrote this is because I didn’t want to install anything new.
I’m really happy my script helps you and you think same as me!

Thanks again!

**Comment by minamotorin** [comment]
After reading your comment, I tried to display all lines in one `print`. But tihs makes the script slow.
Using variables with large values seems to slow down the script more than using multiple `print`.

**Comment by rdv-dev** [comment]
> Using variables with large values seems to slow down the script more than using multiple print.

What an interesting discovery! 

Performance testing is a balance and an art, and making the effort can teach you a lot about how a programming language works. Each language has its own properties which you can take advantage of to find more performance gains, and some techniques are only useful for one language.

Thankfully, printing is something all programming languages share (I think?) and it tends to be slow regardless of language or Operating System, so it is an easy place to start optimizing performance of your program.

Thank you for merging these PRs! This was my first time contributing so I'm very happy this was a positive experience for us both.

**Pull request merged**
